### ISSUE TITLE
gigasecond: use times (not dates) for inputs and outputs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#122]
A duration of a gigasecond should be measured in seconds, not
days.

The `gigasecond` problem has been implemented in a number of languages,
and this issue has been generated for each of these language tracks.
This may already be fixed in this track, if so, please make a note of it
and close the issue.

There has been some discussion about whether or not gigaseconds should
take daylight savings time into account, and the conclusion was "no", since
not all locations observe daylight savings time.

**Comment by soniakeys** [comment]
Comments not specific to Go:

It seems reasonable to me for inputs and outputs to be dates in whole days while a nanosecond is a duration in seconds.  Part of the problem then is type or unit conversion to get the right date for an answer.

I added common test data for this one, https://github.com/exercism/x-common/blob/master/gigasecond.json.  In the process of assembling that I reviewed existing test cases from all languages and found just those three cases shared.  (There was one other case used in one language but I suspected that someone just added their birthdate.)  Those three cases specified dates without times.

To force arithmetic with second-level precision we could add a test case or two with specified non-zero times.   For some languages implementing non-0 times would significantly change the exercise.

I wasn't sure we needed to go there.  After all a birthday or anniversary is usually celebrated by the whole day rather than at a particular time of day.

**Comment by kytrinyx** [comment]
> After all a birthday or anniversary is usually celebrated by the whole day rather than at a particular time of day.

Agreed, however a gigasecond really is about the seconds, and if you happened to be born late in the day, your anniversary might be a day later than you thought. I know that this isn't realistic, but I think that computing seconds rather than days is fairly integral to the problem.

**Comment by soniakeys** [comment]
I'll make up a couple of new test cases with non-0 seconds, try them with Go, then send an x-common PR for the JSON.

**Comment by soniakeys** [comment]
Or, is someone ahead of me?  Are there new test cases in another language I should look at?

**Comment by kytrinyx** [comment]
I don't think anyone is ahead of you.

**Comment by soniakeys** [comment]
Addressed with https://github.com/exercism/x-common/pull/45 and https://github.com/exercism/xgo/pull/124.
