### ISSUE TITLE
Weird order of tests in config.json

### ISSUE THREAD

**Issue by pminten** [exercism/xgo#138]
config.json starts with leap instead of the traditional bob, but also has parallel-letter-frequency before bob. Bob is a trivial exercise while parallel-letter-frequency is somewhat more advanced (it requires using channels and goroutines).

Is there a particular logic to the order of exercises in this track?

**Comment by kytrinyx** [comment]
Leap feels easier than bob, so we moved it ahead in Go. We may have done that in a couple other languages as well. I'm not sure what the thinking was with parallel-letter-frequency. @soniakeys do you recall what happened with that?

**Comment by soniakeys** [comment]
I like parallel letter frequency about where it is.  It needs to come after an exercise or two using maps but otherwise it's a good first exercise with concurrency.  Concurrency is one of the selling points of Go so I like this coming relatively early.

Bob does look a little out of place.  Probably it just got pushed back one exercise at a time as other stuff got inserted in front of it.  It shouldn't come too early because it's got quite a bit going on, a chain of conditional logic, probably at least a couple of functions out of the string library, some program organization decisions, a set of tricky and underspecified rules to puzzle out.  But maybe it could come a little earlier.

This might be good to keep this issue open for a bit and collect some discussion on how things could be ordered.  We might come up with a nice reordering of everything and some ways to keep it ordered in the future.

**Comment by kytrinyx** [comment]
> This might be good to keep this issue open for a bit and collect some discussion on how things could be ordered.

Agreed, this would be a useful discussion.

>  We might come up with [...] some ways to keep it ordered in the future.

@pminten suggested a really interesting approach a while back: https://github.com/exercism/exercism.io/issues/1081

I have not had the time to start working on this (and a whole lot of other things I want to do to improve exercism), but I think it would make things a great deal better.
