### ISSUE TITLE
Add stub files to problems that have a testVersion

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#148]
The testVersion is not documented anywhere, and is a bit tricky for people who are new to Go to figure out.

Since this is a book-keeping thing more than an idiomatic Go / interesting problem solving thing, I think it would make sense to provide a stub file for each of these, defining the test version (see discussion in #145)

- [ ] bob
- [ ] circular-buffer
- [x] clock
- [ ] crypto-square
- [ ] custom-set
- [ ] food-chain
- [x] gigasecond
- [ ] hamming
- [x] leap
- [x] ledger
- [ ] paasio
- [ ] tournament

**Comment by soniakeys** [comment]
I'm not sure what current thoughts are on this issue.  This issue mentions TestVersion but stub files have come up before as a way to communicate other things like API or data types.  I thought maybe stub files might be most needed by people just getting started, and so might be needed just on problems that appear earlier in config.json.  Also, we might write them with more information and more detail for the earlier problems, the let them become more terse and specify fewer details for later problems.

Leap is currently first in config.json so I made a stub file in the branch https://github.com/exercism/xgo/tree/leap-stub.  I didn't send a PR yet because I wasn't sure we wanted this much explanation.

**Comment by kytrinyx** [comment]
Yes, agreed--let's add stub files for the first few exercises, but not necessarily all of them.

I like the idea of starting with a very verbose one, and making them successively more terse. The one thing that could get annoying with that is that most people will probably leave all those comments in place. Perhaps we can remind people to edit the comments to follow the guidelines in https://golang.org/doc/effective_go.html#commentary, deleting any comments that don't seem useful for other people on exercism to see. Perhaps we could even encourage them to run `golint`.

**Comment by soniakeys** [comment]
> most people will probably leave all those comments in place.

I thought of that too.  Hmm, I added a little bit to encourage people to delete the comments, but maybe it could be worded more strongly or maybe we could add that nitpickers would likely criticize them for leaving the comments in.

You know, suggestions for golint and #comentary are in the help file, "getting started with Go".  Maybe that page could use more visibility.  We could mention it here in the stub file but how about maybe mentioning it with the URL in SETUP.md so that it would get included in every README?  (I know, I just merged it.  Maybe I was too fast.)

**Comment by kytrinyx** [comment]
> maybe we could add that nitpickers would likely criticize them for leaving the comments in.

I like that idea, especially since if they do leave it in, the nitpickers will see it and be encouraged to criticize it.

> We could mention it here in the stub file but how about maybe mentioning it with the URL in SETUP.md so that it would get included in every README

Yeah, we should definitely do that.

**Comment by soniakeys** [comment]
Completed with https://github.com/exercism/xgo/pull/186.
