### ISSUE TITLE
Int type used in largest-series-product may be too small

### ISSUE THREAD

**Issue by pminten** [exercism/xgo#157]
The largest-series-product test has this in its test cases:

```go
var tests = []struct {
	digits  string
	span    int
	product int
	ok      bool
}{
...
	{pe1k, 13, 23514624000, true}, // new PE problem
}
```

The problem here is that the number 23514624000 doesn't fit in an int32. In go the type int may be implemented as int32 or int64, most likely based on the machine word size. That means this will work for a 64-bit platform but will likely break at compile time on a 32-bit platform (since you're not allowed to have overflowing constants).

I'm not quite sure how to best fix this though. Changing the result size to int64 would make the most sense but would break user code.

**Comment by soniakeys** [comment]
Mm hm, good catch.  First, breaking code is never a worry, that's what testVersion is for.  We could remove the test case, but I like it because the .yml cites Project Euler.  PE does like to use 64 bits.  Changing the result type sounds better.  You know, I think we could even be devious here and use a type conversion.  We'd move the test program to int64 but instead of comparing the solver's return value directly, convert the type inferred result to int64.  That would let people be sloppy (like I was!) and possibly get nitpicked later.

Huh.  Ideally we'd run CI on multiple architectures.  I don't think Travis offers this.  Their Go page states "Travis CI VMs are 64 bit..."

**Comment by kytrinyx** [comment]
Yeah, I'm pretty sure Travis is linux/64-bit only.

**Comment by pminten** [comment]
I don't think the devious approach would work. The product would overflow during calculation in the user code and then extended to int64 upon return. So correct user code would still be unable to return a correct value.

I'll make a PR for a full conversion to int64 + TestVersion later today.

**Comment by soniakeys** [comment]
Aha.  I got travis to test with 32bit ints:  https://travis-ci.org/exercism/xgo/builds/57178825

It verifies that largest-series-product does indeed fail and also shows that prime-factors has a similar problem.

**Comment by soniakeys** [comment]
As of https://github.com/exercism/xgo/pull/161 and https://github.com/exercism/xgo/pull/162, these problems are int64, and as of https://github.com/exercism/xgo/pull/163 we have CI testing both 32 and 64 bit builds.
