### ISSUE TITLE
Should we swap testVersion and TestVersion?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#177]
I think it would be nice if the solutions don't export TestVersion so that golint doesn't complain.

**Comment by soniakeys** [comment]
Hi Katrina, sorry I haven't been around.  You mean messages like

> example.go:5:7: exported const TestVersion should have comment or be unexported

This doesn't bother me.  We could make the message go away by simply adding a comment.  It might even be nice for the person who is looking at the example solution to try to figure things out.  It could be something like

```
// TestVersion defines a value to match `testVersion` of the test suite.
// This serves as a record of which version of the test suite the solution is written for.
// See [Problem Versioning](https://github.com/exercism/xgo#problem-versioning) in the
// [xgo source](https://github.com/exercism/xgo) README.md.
```

But really, the main purpose of example.go is to serve as a test case for the test suite so CI can test the test program.  I'm not sure it needs to be golint clean.  (But then, I'm not a big fan of golint.)

Regarding the title of the issue, I think we should not swap them.  Exporting a symbol from the test package doesn't make sense.  If we wanted to make the message go away by using an unexported symbol in the solution, I would suggest using a different unexported symbol than the the test program.  Maybe `testVersion` could stay in the test program and `targetTestVersion` could go in solutions.

I suppose when I made up this scheme, I exported TestVersion because my preference is for my test packages to have the _test on the package statement so that I test the exported API and thus test that it is complete and doesn't rely on unexported identifiers.  Exercism doesn't use that scheme, so testing unexported symbols is fine.

mm, so, I see three options:

1.  Do nothing.  I think this is fine.
2.  Add comments to TestVersion definitions in the example.go files.  Some work, but maybe with some advantages of documentation and demonstrating documentation.
3.  Rename TestVersion to something unexported.  Also some work, but perhaps with the advantage that the comment doesn't have to be added to make the golint message go away.

I don't have strong opinions about any of these.

**Comment by kytrinyx** [comment]
I actually don't mind about the `example.go` files, but rather the submissions. If people run golint on their own submission, then they'll get the suggestion of adding a comment to the test version, but it's not really worth commenting, since it's only there for our purposes, not as part of the package itself.

> I suppose when I made up this scheme, I exported TestVersion because my preference is for my test packages to have the _test on the package statement so that I test the exported API.

Yeah, that's a really good point.

I would really like to encourage people to document their code well, not just make golint happy.

I think I need to sleep on it.

Thanks for thinking out loud with me.

**Comment by kytrinyx** [comment]
I've thought about this some more. I've been doing code reviews daily for the past few months, and suggesting that people lint their solutions makes them jump through hoops with their comments. I'd like to swap them around.

**Comment by petertseng** [comment]
Given that we are automating a lot of feedback these days... will rikki complain if `TestVersion` isn't commented? Even rikki doesn't, I run `golint` locally before I submit anyway and output would fatigue me so I have to comment it to silence that.

So I would favor renaming `TestVersion` to `testVersion`. I also think concerns of @soniakeys  about it being weird that tests have an exported variable seem reasonable. So the solution of renaming the original `testVersion` to something like `expectedTestVersion` seems good too.

**Comment by kytrinyx** [comment]
Yeah, rikki- would eventually start complaining about it. I think Sonia's complaint was that it's generally not ideal to test unexported behavior, but I also think using `expectedTestVersion` rather than `TestVersion` in the tests is a good idea. In this case I think that testing exported behavior is fine since it really is just our internal bookkeeping.

I'll tackle this if I have time this weekend.
