### ISSUE TITLE
Why is a build constraint in the exercise template?

### ISSUE THREAD

**Issue by toolness** [exercism/xgo#248]
Hi!

I don't know go, but I just did the first Hello World exercise. And I noticed there were some comments in there that said:

```go
// This next comment is a "build constraint."  It's here for, well, kind of
// complicated testing purposes you don't need to worry about now.
// Actually, you can delete it.

// +build !example
```

This made me chuckle. Is there a point to having it in there, if it doesn't explain what it is and then says I can actually delete it? Or is it in there specifically to make readers laugh? :grin:

**Comment by petertseng** [comment]
Good question. My explanation (which may need corrections because these build constraints were added before my time) follows.

In this repo, we have example solutions to each of the exercises. To make sure that the examples are correct, we have [automated tests](https://travis-ci.org/exercism/xgo) that test each of the examples. But when attempting to compile the tests, if we attempted to compile both the example files *and* the stub files, we would get compilation errors for conflicting definitions.

The [Go docs for build constraints](https://golang.org/pkg/go/build/) tell us that we can use build constraints to control what files get built. And so, we put build constraints on our stub files, then [we instruct our automated tests to exclude the stub files](https://github.com/exercism/xgo/blob/master/.travis.yml#L48).

It's good that you ask this question because I imagine many others had this question before but didn't ask. It makes me wonder, can we come up with a solution that doesn't involve the build constraints? 

What if, for example, we just had the automated tests delete the stub files. If we had the convention that for a directory `exercise-slug` the stub file is named `exercise_slug.go` (true for every one so far except for `hello`) we can delete them with something similar to `for dir in *; do stub=$(echo $dir | tr - _); ls $dir/$stub.go; done`. The benefit is that it would be less confusing. The disdavantage is that we would be bound to that constraint for all stub files we ever write. @kytrinyx , what would you think of this?

**Comment by kytrinyx** [comment]
I commented in the PR, but the summary is this:

Yeah, it would be nice to get rid of these, but I would also like to be able to run the full test suite locally without having to delete stub files, since I can absolutely imagine a future where I would accidentally commit back the deleted file.
