### ISSUE TITLE
Sum Of Multiples incorrect test case

### ISSUE THREAD

**Issue by jrossiter** [exercism/xgo#256]
In the `varTests` test cases for the `Sum Of Multiples` exercise it has:
`{[]int{}, 10000, 0}`

But the accompanying README.md file states: 

> If no set of numbers is given, default to 3 and 5.

Should this test case actually be the following or have I misread the description?
`{[]int{}, 10000, 23331668}`

**Comment by petertseng** [comment]
You're right given the current state of the world.

It's worth noting for historical data why you're right and xgo is wrong. Go's tests [were written in July 2014](https://github.com/exercism/xgo/commit/2c886b7de927cdeb1a162d47ba9caa374b7330fe) before [the default was added in December 2015](https://github.com/exercism/x-common/pull/157).

So either we need to add a Go-specific thing saying "ignore what the readme says, if no factors are given then there are none" or change the test.

As a separate note, worth a survey of the languages seeing what languages are doing with this defaults

**Comment by kytrinyx** [comment]
Having read through this and the older issue, I think that the right move is to improve the problem to remove the "defaults" requirement. I've opened an issue here: https://github.com/exercism/x-common/issues/198

In this case, I believe that the Go exercise is actually correct (though currently confusing because of the thing in the README). Should we just close this issue?

**Comment by petertseng** [comment]
Well... then Go is correct in the sense of "this is where we would like to be eventually". Until all tracks with this exercise are consistent, one side or the other will be confusing (depending on which side the README supports).

So the answer might depend on: How fast will other tracks be able to remove their defaults, and thus when will we be able to remove the default from the README?

Basically it's weighing the costs of temporarily making Go conform to a state that is not the final state we desire versus the cost of confusing those who attempt this exercise in Go (I surveyed languages and Go's the only one that doesn't default).

I'm unsure of my answer to this question because I don't know when to expect https://github.com/exercism/x-common/issues/198 to be done. [Stats](http://exercism.io/stats/go) say there's less than one submission a day.

Alternative could be to stick something in the go tests or something saying "ignore what the readme says about defaults. If no multiples are specified, there are none". I originally had this in my response, but I thought it was weird to have a Go-only exception. But now that I hear that we want this to be the actual behavior, then this could be a thing to do.

**Comment by kytrinyx** [comment]
What if we remove the line in the README right now?

- The Go exercise will not be contradicting the README.
- The other tracks' exercises will not be directly contradicting to the README, but they will have a seemingly odd choice of extension, where the test guides the solution beyond what the README says.

Alternately, I think that your suggestion of sticking a comment in the Go tests is fine. We can even link to the issue as an explanation.

Having typed this out, I think I like your suggestion best.

**Comment by petertseng** [comment]
> The other tracks' exercises will not be directly contradicting to the README, but they will have a seemingly odd choice of extension, where the test guides the solution beyond what the README says.

Hmm, it seems that it can be quite difficult to understand from the tests what the desired defaults are. From looking at [the Ruby tests](https://github.com/exercism/xruby/blob/master/exercises/sum-of-multiples/sum_of_multiples_test.rb) for example, it might not be obvious without experimentation. Some may even be forced to read the example solution to figure that out.

I would have suggested immediately amending the README had it not been for that.

**Comment by kytrinyx** [comment]
That's a good point. OK, let's go with a comment in the Go test suite.
