### ISSUE TITLE
README/development setup: Probably don't need to clone to GOPATH

### ISSUE THREAD

**Issue by petertseng** [exercism/xgo#263]
The README says to clone the repo to my GOPATH, but this does not appear to be necessary... especially since I have the repo outside my GOPATH and I don't have any problems.

Should have a quick check as to whether anything actually needs it, and if not we can remove that from the instructions and just say clone it anywhere you like.

**Comment by kytrinyx** [comment]
I don't have this in my GOPATH, and I've specifically made sure that it works without doing that.

This is particularly because I have all of the language tracks checked out in the same location so that I can run scripts against all of them at the same time.

We can remove that from the instructions.
