### ISSUE TITLE
beer-song: Improve error-handling behavior

### ISSUE THREAD

**Issue by petertseng** [exercism/xgo#282]
As part of #275, we'd like to more closely follow idiomatic Go behavior in the face of errors.

If the beer-song exercise does not have error handling, then this ticket can be closed immediately.

If it does, then follow the below steps:

#### Ensure `err` return value is of type `error`

It's idiomatic for the error return value to be of type `error`.

Most tests simply check whether `err == nil` or not. If we don't verify the type of `err`, it could be any type that has nils.

To lean on the type system, add the following line after assigning err:

```go
var _ error = err
```

See [the hamming tests](https://github.com/exercism/xgo/blob/master/exercises/hamming/hamming_test.go#L14) for an example.

#### Ignore the normal return value when an error expected

The contract in Go is "if there's an error, assume nothing about the normal return value". Thus, we should only check the non-error return value when there is no error.

In some exercises we found that we were checking the normal return value, even when there was an error.

See [the binary tests](https://github.com/exercism/xgo/blob/master/exercises/binary/binary_test.go#L41-L58) for an example of the behavior that we want.

#### Increment the test version

These changes break backwards compatibility. Bump the test version to let reviewers know that the exercise has changed.

This requires changing two constants:

- `targetTestVersion` in the test file (`*_test.go`)

- `testVersion` in the reference solution (`example.go`)

If the exercise does not have a test version, then add one, setting the value to 1.

See [the version test in leap](https://github.com/exercism/xgo/blob/master/exercises/leap/leap_test.go#L13-L15) for an example.

**Comment by petertseng** [comment]
https://github.com/exercism/xgo/pull/368

**Comment by petertseng** [comment]
#368 handled "Ensure `err` return value is of type `error`" but not "Ignore the normal return value when an error expected"

**Comment by andrerfcsantos** [comment]
@petertseng We ran into the `var _ error = err` when doing some updates to the tests for `largest-series-product` and are a bit confused by this bit of code and what is doing. From #381 looks like this was introduced as a compile-time check for the type of `err`, but I'd argue this is not needed. Since `err` is assigned as the second return of functions that return an `error` as the second return value, so even the function returns `nil` as the second value, it'll be a `nil` of type `error`, e.g [this program](https://go.dev/play/p/zT0qaFooDB_0) fails to compile.

> If we don't verify the type of err, it could be any type that has nils.

Can you provide an example of this?

(Sorry to post on an very old closed issue, but I don't know a better place to talk about this)

**Comment by petertseng** [comment]
Here is an example of the code we had in mind.

```go
package main

import "fmt"

func decrementIfPossible(a int) (int, *struct{}) {
	if a == 0 {
		return 0, &struct{}{}
	}
	return a - 1, nil
}

func main() {
	a, err := decrementIfPossible(0)
	if err == nil {
		fmt.Printf("successfully subtracted 1 from 0 to get %d\n", a)
	} else {
		fmt.Println("you can't decrement 0")
	}
}
```

They returned a `*struct{}` from `decrementIfPossible` when they should be returning an `error`.
