### ISSUE TITLE
sum-of-multiples README is confusing, test code (unnecessarily?) expects higher-order function

### ISSUE THREAD

**Issue by matthewfischer** [exercism/xgo#340]
In the sum-of-multiples readme it seems to give some confusing requirements:

> Write a program that, given a number, can find the sum of all the multiples
> of particular numbers up to but not including that number.

Then

> Write a program that can find the sum of the multiples of a given set of
> numbers.

No mention of limits?

Then the test code is odd because it seems to be calling the test function twice. Unless this was intentionally obfuscated, I think some terminology like "Write a function that takes a number of factors and returns a function which is then called with the limit and returns the sum of all the factors up to the limit" (actually that's pretty horrible, but I think something about returning a function here and more clarity would help.

**Comment by petertseng** [comment]
>> Write a program that can find the sum of the multiples of a given set of numbers.
>
> No mention of limits?

I think it would be better if that would mention the limit The place to fix it is https://github.com/exercism/x-common/blob/master/sum-of-multiples.md .

> Then the test code is odd because it seems to be calling the test function twice.

I took a look. Interesting interface. Rationale documented in https://github.com/exercism/xgo/pull/53. Were it up to me I would have gone with a more conventional interface, really, of just `SumOfMultiples(limit int, multplies []int) int`.

I recognise there can be value in working with higher order functions, though this exercise doesn't necessarily have to be it.

It would be possible to document the interface either in the test file, or in a HINTS.md (this gets [appended to the README](https://github.com/exercism/x-api/blob/78ce4b95db5d1c97520145cdeef7f8ce49f3041f/lib/xapi/implementation.rb#L101))

**Comment by petertseng** [comment]
> I recognise there can be value in working with higher order functions, though this exercise doesn't necessarily have to be it.

Accumulate has a function that takes a function. sum of multiples is the only function that returns a function right now.

**Comment by petertseng** [comment]
EBWODP: My recommendation is to change `SumOfMultiples` to use a conventional interface without the higher-order function, and if possible find an exercise where it makes more sense to have a function that returns a function.

**Comment by ahammond** [comment]
Is the challenge of this question intended to be decoding an interface that is broken by design? I'm here to learn golang, not reverse engineering legacy turds. That's my day job. :)

**Comment by petertseng** [comment]
> Is the challenge of this question intended to be decoding an interface that is broken by design?

All I can infer from #53 is that the interface in its current state was intentional.

I have [argued elsewhere](https://github.com/exercism/x-common/pull/400#issuecomment-253422870) that exercises should only test what is essential to their problem statements.

My opinion is that the current interface is un-natural compared to how this problem would normally be solved in Golang - and therefore it is testing something un-essential to its problem. If there is a strong desire to introduce functions that return other functions, it should be in another exercise.

My recommendation remains that this track should change sum-of-multiples to use an interface resembling `SumOfMultiples(limit int, multiples []int) int`. Do not wait for a new exercise introducing functions that return other functions; the new exercise can come later.
