### ISSUE TITLE
[secret-handshake] is code = 33 valid?

### ISSUE THREAD

**Issue by NobbZ** [exercism/xgo#359]
The README.md states:

> The program should consider strings specifying an invalid binary as the value 0.

Also it does specify a meaning for the bits `0` to `4` (0 meaning LSB; counting to MSB). It does not spcify a meaning for bit 5, so I would assume, that any input that has any bit greater than 4 set is invalid.

But in fact, the tests expect negative values to be invalid, but positiv values shall be treated as if they had only 5 bits set.

This is in my opinion counter intuitive, so I want to ask if there is any reasoning behind this?

**Comment by NobbZ** [comment]
I will try to rephrase a bit and consider int to be signed (because we have a -1) and 8 bit (makes it easier to follow and argue about). Also I will assume we use [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) for negative numbers.

It will refer to the bits by numbers, as shown below:

```plain
MSB 76543210 LSB
```

The README does specify how to interpret the bits 0 to 4, but not 5, 6, and 7. Also it says that we shall treat invalid input as 0.

Further we have tests asking for -1 and 33, which are in bit representation like this:

```plain
MSB  76543210  LSB
- 1: 11111111
 33: 00100001
127: 01111111 (not in tests)
```

I did also add 127 as another case. According to the example implementation it is a valid sample, but it is only a single bit that makes it different to -1.

Even worse if, we'd use unsigned ints, the exact same binary `11111111` would be valid all of a sudden.

Is there any reasoning behind this unpredicatable behaviour?

@exercism/golang

**Comment by petertseng** [comment]
As I can see, in the beginning, at https://github.com/exercism/xgo/commit/4ec2549c6775e1a33f16a3d32e372a9c4480901d - both -1 and 32 were in error. then at https://github.com/exercism/xgo/commit/2328a46b3787fcd6ffafa72d5bd10ac487b2c6bc 33 was declared to be in error. Then at #173, 33 was changed to not be an error.

Personally, I think in any context where we care about what bits are set, one should always use unsigned integers. There are two negative consequences of using signed integers. The first is that you lose a bit

```go
package main

import (
	"fmt"
)

func main() {
	var a int8 = 0x80
	fmt.Printf("Hi %x\n", a)
}
```

That's a compiler error, `tmp/sandbox740920875/main.go:8: constant 128 overflows int8`

Sure, we could simply remember that that's -128, but this is not nearly as convenient, and also annoying when you want to set multiple bits and one of those bits is the MSB.

The second reason is if you are shifting a bit pattern that includes the MSB it is highly likely you want a logical (zero-extending) shfit rather than an arithmetic (sign-extending) shift. And Go only has the sign-extending variety. So if you used signed integers your `10101010 >> 3` will be `11110101` instead of `00010101` as it would be with unsigned integers.

So as it pertains to this track, both secret-handshake and allergies should use unsigned integers, since they deal with bit patterns. After that, it's not important to me personally whether numbers out of the specified range just get masked, or if they produce an error.

**Comment by kytrinyx** [comment]
> as it pertains to this track, both secret-handshake and allergies should use unsigned integers, since they deal with bit patterns

I agree.

> After that, it's not important to me personally whether numbers out of the specified range just get masked, or if they produce an error.

Based on my experience with using bitmasking in real-world situations, I would lean slightly towards ignoring numbers outside of the specified range, but I really don't have strong feelings about it.

**Comment by petertseng** [comment]
Okay, so I think the thing to do is to use unsigned integers, and then there will not be the question of inconsistency for the negatives. So that's #373 and #374.
