### ISSUE TITLE
Investigate track health and status of the track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#415]
I've used Sarah Sharp's [FOSS Heartbeat](https://github.com/sarahsharp/foss-heartbeat) project to generate stats for each of the language track repositories, as well as the x-common repository.

The Exercism heartbeat data is published here: https://exercism.github.io/heartbeat/

When looking at the data, please disregard any activity from me (`kytrinyx`), as I would like to get the language tracks to a point where they are entirely maintained by the community.

Please take a look at the heartbeat data for this track, and answer the following questions:

* To what degree is the track maintained?
* Who (if anyone) is merging pull requests?
* Who (if anyone) is reviewing pull requests?
* Is there someone who is not merging pull requests, but who comments on issues and pull requests, has thoughtful feedback, and is generally helpful? If so, maybe we can invite them to be a maintainer on the track.

I've made up the following scale:

* **ORPHANED** - Nobody (other than me) has merged anything in the past year.
* **ENDANGERED** - Somewhere between ORPHANED and AT RISK.
* **AT RISK** - Two people (other than me) are actively discussing issues and reviewing and merging pull requests.
* **MAINTAINED** - Three or more people (other than me) are actively discussing issues and reviewing and merging pull requests.

It would also be useful to know if there a lot of activity on the track, or just the occasional issue or comment.

Please report the current status of the track, including your best guess on the above scale, back to the top-level issue in the discussions repository: https://github.com/exercism/discussions/issues/97

**Comment by petertseng** [comment]
Hello everyone. I have submitted the report for our track at https://github.com/exercism/discussions/issues/97#issuecomment-261943473

For any contributors here who are interested, yet disappointed I didn't mention you - fear not! We candefinitely talk about your contributing more and taking on a greater role in the track.

**Comment by ferhatelmas** [comment]
@petertseng I really liked our previous discussions and I'd like to contribute/help more. 

My first preference is go but not particularly. You can count me in order for any endangered track. If anything is needed to show my willingness, please let me know.

**Comment by petertseng** [comment]
All right! Well, the "show willingness" part will basically be looking through https://github.com/exercism/exercism.io/blob/master/docs/maintaining-a-track.md and being sure that these are things you would like to do. There is no pressure on that front though - contributions are accepted from everyone, not just maintainers!

I have sent an email, but you can feel free to reply there or here!

**Comment by petertseng** [comment]
Well, might as well write in here with a short update on this. Because even though the Exercism-wide health check-in has ended, it is useful to keep a pulse on our health, right?

With @bordeltabernacle joining us about two weeks ago, and still excluding Katrina since she asks to be excluded, this track now has three recently-active maintainers.

Of course, any maintainers who were once around but just have been inactive recently will be welcomed back with open arms, we miss you! You're still on the team as well, so can jump back in at any time really.

I mentioned in my report for this track (https://github.com/exercism/discussions/issues/97#issuecomment-261943473):

> Active improvements to the track and fixes for issues are not being made by the maintainers themselves, but in general pull requests from contributors are being accepted.

We're getting some improvements nowadays, thanks everyone.

I will note that the above sentence may be true *for me personally* for some time, due to a combination of non-Exercism-related duties and plus I have my hands in what some people will argue is too many Exercism tracks. You may not see me personally make a lot of PRs to this track (you can look at [the list](https://github.com/exercism/xgo/pulls?q=is%3Apr+author%3Apetertseng) and see that the activity fell off sharply the past year, only four in the last half of 2016!), but I feel I'm at least still competent to review others' changes.

Don't feel pressured to reluctantly make changes out of some obligation (as has [been said before](https://github.com/exercism/discussions/issues/105#issuecomment-264224702), "the only commitment is the one you make with yourself. :)"), hope everyone's still making changes because they're getting something useful out of it. Hope we can keep moving the track forward!

**Comment by bordeltabernacle** [comment]
Personally, since becoming a maintainer, I've felt really enthusiastic about making changes. I'm a lone developer at work at it feels really good to be working within a team, on a shared project. I certainly intend to keep adding my two cents while it's still worthwhile, and not out of any pressure or guilt, only the enjoyment of writing code and a belief in exercism.

**Comment by kytrinyx** [comment]
> [E]ven though the Exercism-wide health check-in has ended, it is useful to keep a pulse on our health, right?

Yes, very much so! It would probably be useful to run an Exercism-wide healthcheck on a regular basis.

> since becoming a maintainer, I've felt really enthusiastic about making changes

I'm so excited to hear this! :sparkles:
