### ISSUE TITLE
Consider using Example tests for some exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xgo#420]
One thing that would perhaps lower the barrier even further on the Hello World exercise is to use Example tests, make it a `main` package with a `main` function, and just have people write to standard out.

What do you think?

/cc @ardan-bkennedy for the suggestion
/cc @petertseng @ferhatelmas as maintainers on the track

**Comment by petertseng** [comment]
By example tests, does this mean a separate function to test each case (currently "" and "Gopher") rather than one function performing a table-based test?

Or does it mean https://golang.org/pkg/testing/#hdr-Examples which I did not know existed until I searched for it just now?

Should any other exercises do this? It is good to get exposed to other techniques. It might be a bit jarring to students if hello world does it one way and then all other exercises do it another way. So should this be used in some other exercises too?

**Comment by ardan-bkennedy** [comment]
I don't think it needs to be an all or nothing with the type of tests. There are many exercises where printing to stdout can make the exercise simpler. Using an example test can simplify everything. Just writing out "Hello, World" and on the next line "Hello, Gopher" would be simple.

When it comes to more of the concurrency exercises, writing to stdout could also allow for more interesting exercises.

**Comment by kytrinyx** [comment]
@petertseng I meant the second one (https://golang.org/pkg/testing/#hdr-Examples).

> Should any other exercises do this?

Yeah, I think we should consider using it for some of the other exercises as well. I think it's worth exposing people to the different types of testing that the standard library has.

**Comment by robphoenix** [comment]
I was initially quite confused about Example tests, and started off implementing them in a couple of exercises as a replacement for the current table-driven tests. This didn't initially feel quite right as doing this would mean we wouldn't be able to take advantage of the test cases generation. 

So, my understanding of the example tests, helped enormously by [this](https://blog.golang.org/examples), is that they're similar to Python's doctests and can be useful for clarifying, and verifying, the API expected of an exercise. This can be very useful for exercises such as clock, where I've seen confusion before regarding what is expected (#448).

As such I've opened #568. I don't know if we want to use only example tests, in place of the current mostly table driven tests, in some exercises? I don't expect we will need or want Example tests in all exercises, as this may make things too obvious. I hope I've not totally misunderstood and that #568 introduces Example tests in a meaningful way. If nothing else it helped me to understand what they are and how to use them (surely there's a blog post in that! :thinking: )

**Comment by kytrinyx** [comment]
> surely there's a blog post in that!

Indeed!

How about Example tests for the new `two-fer` exercise? https://github.com/exercism/x-common/issues/548 For that, we could make it so that the code actually prints to stdout instead of returning strings.

Or maybe one of the text-heavy ones (`house`, `beer-song`, `twelve-days` or `food-chain`, keeping the discussion from https://github.com/exercism/x-common/issues/326 in mind).

**Comment by robphoenix** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add further Example Tests](https://trello.com/c/FPPyDCsJ/1-add-further-example-tests)

**Comment by robphoenix** [comment]
Yes, I think the two-fer exercise would be a good candidate for this, I'll look into getting that exercise implemented. 

I'm not so sure about the text-heavy exercises, because they are so text heavy. The tests as they are are less straightforward so they can help the user pinpoint their error when the tests fail. With an example test if all that's happening is comparing two large blocks of text that may have a minimal difference, such as a new line, it may be dispiriting to not have some kind of indication as to where you're going wrong. Therefore I think a simpler, shorter test output would perhaps be more appropriate, like acronym, or Bob.

If we do want to use only example tests for some exercises it's worth considering this in the context of the tracks use of generators. In my mind I can't see why we couldn't also generate the example test files, it would mean the generator would have to create a different filename depending on the type of test; cases_test.go / example_test.go

**Comment by robphoenix** [comment]
Just as an aside, this issue has directly led to my first commit in to the Go language itself; https://github.com/golang/go/commit/716761b8b13926ef4a82dcb4ffc324066779239c so thanks again @kytrinyx for being such a positive influence on me and my life in code.

**Comment by kytrinyx** [comment]
> this issue has directly led to my first commit in to the Go language itself

That is so cool! ✨ Congrats!!!

And thank you. ❤️

**Comment by tleen** [comment]
The way I am reading it is that Tests are to test an API, and Example Tests are to generate documentation examples. The actual output testing of those exists to verify that the documentation is accurate. 

With the idea that you are coming into this track without knowing Go much, the idea of example tests is foreign, while the idea of standard tests to see if an api is producing expected output is more normal.

That being said I can see a place where we would want to document how API is expected to work in the test file. I generally have to start exercises looking for what the API is supposed to be in the test files because that is the only specific formal documentation as to what the input/output. Examples of the api/expected output would be helpful in these cases.

Either way this should be really well explained in the first (few?) exercises in the track. It's not an obvious thing at all if you are just getting into Go from another language.

**Comment by kytrinyx** [comment]
> Either way this should be really well explained in the first (few?) exercises in the track. It's not an obvious thing at all if you are just getting into Go from another language.

So true! 💯
