### ISSUE TITLE
Generating tests references most recent commit, not relevant commit

### ISSUE THREAD

**Issue by bordeltabernacle** [exercism/xgo#445]
In updating the `leap` exercise tests in #444 the `example_gen.go` script adds in the most recent x-common commit:

```
// Commit: cfdae36 Merge pull request #497 from exercism/stkent-patch-1
```

which has no relevance to the updated leap tests, which were changed in [this commit](https://github.com/exercism/x-common/pull/463)

I don't know the test generation code well enough, or git well enough, to fix this currently, but will try and spend some time this week understanding it better.

In the meantime I wanted to check if this was known and deliberate or if someone else was easily able to fix if not?

**Comment by petertseng** [comment]
How does the generator even *know* what commit it is? I'll read the code real quick...


oh, it just does `exec.Command` on `git log`.

Pass the filename of the JSON file into that `git log` command, and it should be all good.

Compare the effects of running these two commands in the `x-common` repo:

```
git log -1 --oneline
git log -1 --oneline exercises/leap/canonical-data.json
```

Should be a good fix to make, because we should keep the commit relevant.
