### ISSUE TITLE
Ensure consistency across exercise tests

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#470]
#465 highlighted certain test file inconsistencies between the exercises.
These were:

1. lack of `testVersion/targetTestVersion` for all exercises, initialised at 1, to be incremented upon significant changes
2. separate `TestTestVersion` function, rather than as part of main test function
3. placement of `TestTestVersion` function as the first test function
4. `TestTestVersion` function using `Fatalf` rather than `Errorf`

**Comment by robphoenix** [comment]
- [ ] accumulate
- [ ] acronym
- [ ] all-your-base
- [ ] allergies
- [ ] anagram
- [ ] atbash-cipher
- [ ] bank-account
- [ ] beer-song
- [ ] binary-search-tree
- [ ] binary-search
- [ ] binary
- [ ] bob
- [ ] bracket-push
- [ ] circular-buffer
- [ ] clock
- [ ] connect
- [ ] counter
- [ ] crypto-square
- [ ] custom-set
- [ ] diamond
- [ ] difference-of-squares
- [ ] diffie-hellman
- [ ] error-handling
- [ ] etl
- [ ] food-chain
- [ ] gigasecond
- [ ] grade-school
- [ ] grains
- [ ] hamming
- [ ] hello-world
- [ ] hexadecimal
- [ ] house
- [ ] isogram
- [ ] kindergarten-garden
- [ ] largest-series-product
- [ ] leap
- [ ] ledger
- [ ] luhn
- [ ] matrix
- [ ] meetup
- [ ] minesweeper
- [ ] nth-prime
- [ ] nucleotide-count
- [ ] ocr-numbers
- [ ] octal
- [ ] paasio
- [ ] palindrome-products
- [ ] pangram
- [ ] parallel-letter-frequency
- [ ] pascals-triangle
- [ ] perfect-numbers
- [ ] phone-number
- [ ] pig-latin
- [ ] poker
- [ ] pov
- [ ] prime-factors
- [ ] protein-translation
- [ ] pythagorean-triplet
- [ ] queen-attack
- [ ] raindrops
- [ ] react
- [ ] rna-transcription
- [ ] robot-name
- [ ] robot-simulator
- [ ] roman-numerals
- [ ] saddle-points
- [ ] say
- [ ] scrabble-score
- [ ] secret-handshake
- [ ] series
- [ ] sieve
- [ ] simple-cipher
- [ ] strain
- [ ] sum-of-multiples
- [ ] tournament
- [ ] transpose
- [ ] tree-building
- [ ] triangle
- [ ] trinary
- [ ] twelve-days
- [ ] variable-length-quantity
- [ ] word-count
- [ ] word-search
- [ ] wordy

**Comment by tleen** [comment]
acronym is already ok

**Comment by tleen** [comment]
Should we be skipping [counter](https://github.com/exercism/xgo/tree/master/exercises/counter) in this? It has been [deprecated](https://github.com/exercism/x-common/issues/80), and its very nature seems to turn the idea of "consistency" in tests topsy-turvy.

**Comment by petertseng** [comment]
> Should we be skipping counter in this?

yeah seems good. and even if it wasn't deprecated... we didn't provide any tests in counter, which means there's nothing to really version.

**Comment by tleen** [comment]
custom-set can be checked off, it is already consistent.

**Comment by petertseng** [comment]
> custom-set can be checked off

Checking it off (deleting this comment after the email sends)

**Comment by kytrinyx** [comment]
> placement of TestTestVersion function as the first test function

I'm late to the party. Since the test version is more for the reviewers than the people solving the problem, I think it would be worth considering making the testVersion last, not first. That way it's only an afterthought/formality, rather than the first thing they have to do.

Or we could provide a stub file with the testVersion already supplied.

**Comment by kytrinyx** [comment]
Ah, I just saw this comment by @robphoenix 

> So, after a little [digging](https://gophers.slack.com/archives/general/p1485781892036688), it appears tests within a single package are run sequentially, unless marked with [`t.Parallel()`](https://golang.org/pkg/testing/#T.Parallel), therefore is it worth ensuring the test version is correct before running any specific exercise tests?

This is a good point. Maybe putting it first is the right way to go.

I think at this point I could go either way. I'll defer to the rest of you.

**Comment by tleen** [comment]
I ended up buying into the idea that we should have the test version testing run first. If not, users could be getting errors related to differences between test and the exercise version which could lead to unexpected and frustrating errors.

If anything we should emphasize the test versioning concept in [Hello World](exercises/hello-world/) so that it becomes an obvious thing for users as they view following exercises. Having all the exercises consistent in how they utilize that concept will help. Eventually it should just fade into boilerplate territory for the users.

**Comment by kytrinyx** [comment]
@tleen Agreed—I think you're right that if we emphasize it for hello world, it removes potential confusion and it will just fade into boilerplate territory. 👍

**Comment by tleen** [comment]
Ok. I just committed Hello World with the consistent arrangement. Will add an issue for better documenting the testing setup in that exercise.

**Comment by tleen** [comment]
I believe this is accomplished?

:four_leaf_clover: :smile:

**Comment by robphoenix** [comment]
@tleen you're a test consistency powerhouse! :muscle:

**Comment by tleen** [comment]
Good stuff. I'll close this one out. :+1:

**Comment by petertseng** [comment]
Nice work doing this for all 80 of our exercises! (Plus the deprecated ones, I believe that makes it 85)

If y'all are thinking of other things to do, could consider ensuring that all exercises in x-common that have canonical-data.json have a test generator, and that the test generators still run (due to recent schema changes, some generators might require changes). This can help our track more easily keep up with changes to x-common (just rerun the generator, and we are done!).

No obligation to take this suggestion, since I don't consider myself to hold any special authority here; just whatever makes our lives as maintainers easier.

**Comment by tleen** [comment]
Sure. I'm sort of swamped at work till mid-April but if you make an issue for this we can slowly work our way through it like with the test versioning.

**Comment by robphoenix** [comment]
I'd been thinking this same thing. I'll make a start on it in the coming weeks also.

**Comment by petertseng** [comment]
OK. I can't start to make the issue for the next 4 hours. I will do it after that, unless one of you says you are before then.
