### ISSUE TITLE
Is the example_gen.go file appropriately named?

### ISSUE THREAD

**Issue by robphoenix** [exercism/xgo#607]
One thing that I've always been a little unsure of is the filename `example_gen.go`. It's never struck me as descriptively reflective of what it is. Unless I'm missing something, my assumption is that originally it was an example of a generator for an exercise and an appropriate naming convention was never decided upon? 

At this point of going through the process of updating/creating generators I'd like to suggest a potential change of filename. The current name gives the impression it generates the `example.go` file. So, I was thinking something like `test_cases_gen.go` or `<exercise_name>_gen.go`, though it's probably easier to keep the name the same across the exercises.

**Comment by petertseng** [comment]
I would guess that the reason for it being called example_gen.go is simply so that it doesn't get delivered to students, since anything with `example` is ignored: https://github.com/exercism/trackler/blob/master/lib/trackler/implementation.rb#L9

You could look at the very first generator in #115 (there is not that much explanation for the naming rationale)

I questioned this in https://github.com/exercism/x-api/issues/113 and the result was the creation of .meta - so we could put the generator for `leap` in `exercises/leap/.meta/generator.go` if we like.

Alternatively, we could place the generator for `leap` in `gen`, outside of the `exercises` directory.

**Comment by robphoenix** [comment]
Ah, that's interesting, ok, great. I think making use of .meta would be most appropriate.
 I'll open a PR moving the current files and update the docs and current issues, tomorrow hopefully.
I suppose there's no immediate reason to move the example solution file in to  .meta yet also?
And are there strong feelings regarding the generator file name? Otherwise I'll just go with generator.go or gen.go

**Comment by petertseng** [comment]
> I suppose there's no immediate reason to move the example solution file in to .meta yet also?

I don't have a reason; seems fine to leave it so that it's easier to test with `go test` (otherwise you have to move it)
