### ISSUE TITLE
triangle exercise bad idea

### ISSUE THREAD

**Issue by splace** [exercism/xgo#678]
because it perpetuates the idea that its fine to compare two floats for equality.

the reason you should never do that, is because the result will be dependent on the representation, and other non-obvious things and also people are even more confused because it often works as expected, but then will stop unexpectedly.

understanding why this is, is a fundamental principle see;  https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems

**Comment by petertseng** [comment]
Thanks. It would be to your advantage to remove https://github.com/exercism/x-common/blob/master/exercises/triangle/canonical-data.json#L55 and https://github.com/exercism/x-common/blob/master/exercises/triangle/canonical-data.json#L106 and https://github.com/exercism/x-common/blob/master/exercises/triangle/canonical-data.json#L145 citing this same reasoning. Otherwise, there is no guarantee other tracks won't do the same.

As for this track:

If the maintainers of this track agree, then it seems like removing all float cases (including the NaN and infinities) will address this.

**Comment by splace** [comment]
the problem is hard to explain, but...

to always be able to determining if a triangle is equilateral requires infinite precision, its a euclidean definition, and computers cannot do that.  

this general misunderstanding produces a lot of bugs in code.

in the example the input coordinates have limited precision so it can work, but it gives people a false idea, that it will always work, its a incorrect concept that teaching examples shouldn't be re-enforcing.

there are probably other examples doing this, this is the only one i saw.

i see this is repeated in many languages, so i'm feeling like this; 
![](https://imgs.xkcd.com/comics/duty_calls.png)

**Comment by petertseng** [comment]
> i see this is repeated in many languages

that only makes it all the more important that this issue be filed in x-common instead of being limited to this track.

**Comment by splace** [comment]
i will put an issue up there.
