### ISSUE TITLE
provide implementation file

### ISSUE THREAD

**Issue by mattetti** [exercism/xgo#97]
As a new user, I found confusing that I didn't have a blank file with the package name and the basic API to implement.

**Comment by pminten** [comment]
This is an old issue and I'm not sure if it's intended to still be open, but I just wanted to add that the problem with having both a stub file and an example is easy to solve by using build tags.

The ledger test has that problem on steroids since it has two full implementations (a crappy one that the user has to refactor and a less crappy example). What I did there was to add at the top of the example.go file a comment line `// +build example` and at the top of the exercise file (ledger.go) a comment line `// +build !example`. The travis scripts run `go test -tags example` so they test the example file and ignore the exercise file.

**Comment by kytrinyx** [comment]
Good point. I'm not actually sure if we came to any conclusion with this. I think it could be useful to do it only for the first exercise to help first-time users / first-time Go programmers, but I actually like that most of the time it's up to the user to read the error messages and look at the test code to figure out what to do.

**Comment by soniakeys** [comment]
The first few exercises have stub files now.  I think we can finally close this one.
